morpho-org/vault-v2

src/VaultV2.sol
src/libraries/EventsLib.sol
test/SettersTest.sol

fixes chainsec 7.5
open to proposals on the naming

feat: event in timelocked (chainsec 7.5)

---

src/VaultV2.sol

fixes https://cantina.xyz/code/523e1540-f8c3-45ae-9c5d-b6d35d3a326c/findings/555

docs: small losses (competition 555)

---

README.md
certora/specs/PreviewFunctions.spec
src/VaultV2.sol
src/interfaces/IVic.sol
src/vic/ManualVic.sol
src/vic/SingleMorphoVaultV1Vic.sol
test/ManualVicTest.sol
test/SingleMorphoVaultV1VicTest.sol
test/integration/SingleMorphoVaultV1VicIntegrationTest.sol

this also makes the "IPS rounding problem" better

fix: deadline issue (competition 309)

---

src/adapters/MorphoVaultV1Adapter.sol

fixes https://cantina.xyz/code/523e1540-f8c3-45ae-9c5d-b6d35d3a326c/findings/15

docs: document unskimmable shares (competition 15)

---

src/VaultV2.sol

fixes https://cantina.xyz/code/523e1540-f8c3-45ae-9c5d-b6d35d3a326c/findings/207

docs: liquidity market cap (competition 207)

---

src/VaultV2.sol

fixes https://cantina.xyz/code/523e1540-f8c3-45ae-9c5d-b6d35d3a326c/findings/527

docs: document penalty redistribution (competition 527)

---

src/VaultV2.sol
src/interfaces/IVaultV2.sol
src/libraries/ErrorsLib.sol
test/AccrueInterestTest.sol
test/BaseTest.sol
test/RealizeLossTest.sol
test/integration/MorphoVaultV1IntegrationDepositTest.sol

fixes the shares shorting issue without enterBlocked

one accrue per tx

---

src/adapters/interfaces/IMorphoMarketV1Adapter.sol
src/adapters/interfaces/IMorphoVaultV1Adapter.sol
test/MorphoMarketV1AdapterTest.sol
test/MorphoVaultV1AdapterTest.sol
test/integration/MorphoMarketV1IntegrationTest.sol
test/integration/MorphoVaultV1IntegrationTest.sol
test/integration/MorphoVaultV1_1IntegrationTest.sol

chore: update adapters interface

---

.github/workflows/certora.yml
certora/confs/TokensNoAdapter.conf
certora/specs/TokensMorphoMarketV1Adapter.spec
certora/specs/TokensMorphoVaultV1Adapter.spec
certora/specs/TokensNoAdapter.spec

This PR adds a spec for token flow when liquidity market adapter is unset.

[Certora] Tokens no adapter

---

src/libraries/MathLib.sol
test/AccrueInterestTest.sol
test/AllocateTest.sol
test/MorphoMarketV1AdapterTest.sol
test/MorphoVaultV1AdapterTest.sol
test/integration/MorphoMarketV1IntegrationBadDebtTest.sol
test/integration/MorphoMarketV1IntegrationInterestTest.sol
test/integration/MorphoVaultV1IntegrationBadDebtTest.sol
test/integration/MorphoVaultV1IntegrationInterestTest.sol
test/integration/MorphoVaultV1_1IntegrationBadDebtTest.sol
test/integration/MorphoVaultV1_1IntegrationInterestTest.sol

- fixes #691 
- fixes #675 
- fixes #651 
- fixes #674

test improvements 

---

src/VaultV2.sol

fixes https://github.com/sherlock-audit/2025-08-morpho-vault-v2-aug-13th/issues/27

fix: document performance fee

---

src/VaultV2.sol

fixes https://github.com/sherlock-audit/2025-08-morpho-vault-v2-aug-13th/issues/29

fix: document no internal slippage check

---

src/VaultV2.sol

fixes https://github.com/sherlock-audit/2025-08-morpho-vault-v2-aug-13th/issues/39

fix: document caps can be exceeded

---

src/adapters/MorphoMarketV1AdapterFactory.sol
src/adapters/interfaces/IMorphoMarketV1AdapterFactory.sol
test/MorphoMarketV1AdapterTest.sol

fixes: https://cantina.xyz/code/36c2cec0-15bb-4aaa-8ad9-93e08fa71081/findings?finding=1

fix: event morpho market v1 adapter factory

---

src/adapters/MorphoMarketV1Adapter.sol
src/adapters/MorphoVaultV1Adapter.sol

fixes https://github.com/sherlock-audit/2025-08-morpho-vault-v2-aug-13th/issues/37

fix: document unique id

---

src/VaultV2.sol

replaces #729 
fixes https://cantina.xyz/code/36c2cec0-15bb-4aaa-8ad9-93e08fa71081/findings?finding=3

fix: document remove allocator

---

src/VaultV2.sol

fixes https://github.com/sherlock-audit/2025-08-morpho-vault-v2-aug-13th/issues/36

document position underestimate

---

.github/workflows/certora.yml
certora/confs/AbdicatedFunctions.conf
certora/confs/Invariants.conf
certora/confs/Liveness.conf
certora/confs/MorphoMarketV1AdapterFactory.conf
certora/confs/MorphoVaultV1AdapterFactory.conf
certora/confs/OwnerSafety.conf
certora/confs/PreviewFunctions.conf
certora/confs/Reentrancy.conf
certora/confs/SentinelLiveness.conf
certora/confs/TokensMorphoMarketV1Adapter.conf
certora/confs/TokensMorphoVaultV1Adapter.conf
certora/confs/TokensNoAdapter.conf

mirror of #697, without the fmt

[Certora] prover v8

---

src/VaultV2.sol

fixes https://github.com/sherlock-audit/2025-08-morpho-vault-v2-aug-13th/issues/34

fix: document relative cap liquidity market small vault

---

src/VaultV2.sol

See https://github.com/morpho-org/vault-v2/pull/722#discussion_r2368526841

docs: submit change to timelock of decreaseTimelock
